### ISSUE TITLE
Translation missing on solidus_multi_domain:install

### ISSUE THREAD

**Issue by ajkamel** [solidusio/solidus_multi_domain#32] opened 2016-03-12 17:44 UTC
When adding multi_domain to my existing Solidus application I run into this error here

 **https://gist.github.com/ajkamel/af51b08def4748afda47**

`i18n-0.7.0/lib/i18n.rb:311:in 'handle_exception': translation missing: en.spree.validation.must_be_int (I18n::MissingTranslationData)`

Im currently using solidus 1.2.2.  As @clarke mentioned this was removed on master.  When inspecting the gem the translation is still existing in my current 1.2.2 gem directory.

**Comment by ajkamel** [comment] 2016-03-12 19:00
I was able to by pass this by using the current master branch 1.3 - alpha for Solidus however since the current stable is 1.2.2 is it recommended that we wait until 1.3 is released?

**Comment by adammathys** [comment] 2016-03-15 23:54
I've been unable to reproduce this issue. I setup a new Rails app with the following Gemfile:

```ruby
source 'https://rubygems.org'

gem 'rails', '4.2.6'

gem 'sqlite3'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'

gem "solidus", "~> 1.2.2"
gem "solidus_auth_devise"

gem "solidus_multi_domain"

group :development do
  gem "quiet_assets"
end
```

Running `rails g solidus_multi_domain:install` completes without issue for me. Is there any additional information you could provide?

**Comment by adammathys** [comment] 2016-05-27 21:52
Going to close this issue. If you're still experiencing the problem please let me know.

**Closed by adammathys** 2016-05-27 21:52 UTC
